- name: configure catalogue component
  hosts: catalogue
  become: yes

  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20 version
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs:20 vertsion
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Creating roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

# this module - unarchive thinks file exits on ansible control server, but needs to extract on remote machine[catalogue server]
# remote_src: yes , means here file is already exist in catalogue server
    - name: unzipping the catalogue code into /app directory
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

# for npm dependencies, the is no ansibile module, but community module is there
    - name: Install dependencies for npm 
      community.general.npm:
        path: /app

# Creating servive file for catalogue and this an task,

    - name: copy catalogue service to /etc/systemd/system/catalogue.service location
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

#deamon reload
    - name: daemon reload - systemd - systemctl
      ansible.builtin.systemd_service:
        daemon_reload: true

# start and enable catalogue service
    - name: start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

# To have mongo client installed we have to setup MongoDB repo and install mongodb-client.
    - name: copying mongo.repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

# installing mongo db client
    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

# load the products data to mongo db

    - name: Check load products data or not
      ansible.builtin.command: mongosh --host mongodb.muruga.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    # printing above catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    # load products in mongodb server if [stdout": "-1"] -> stdout less than 0, if greater than zero means products already loaded

    - name: load products into mongodb server
      ansible.builtin.command: mongosh --host mongodb.muruga.site </app/db/master-data.js
      # here in below when contion, the catalogue output ll come as string, so just convert it to integer, serch in google like, convert a string to int in single line for ansible...
      when: catalogue_output.stdout | int < 0

     







