- name: Confuring the shipping micro service 
  hosts: shipping
  become: yes

  tasks:
    - name: Install Maven # which takes care of java installation automatically
      ansible.builtin.package:
        name: maven 
        state: present

    - name: Create system user
      ansible.builtin.user:
        name: roboshop
        home: /app
        shell: /sbin/nologin
        system: true

    - name: Create home directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download application in /tmp/shipping.zip location
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: Unzipping shipping code to /app directory
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
# changing specific directory to install mvn clean package and comes back from that directoiry.....
    - name: Install maven dependencies
      ansible.builtin.command: mvn clean package 
      args:
        chdir: /app







